[package]
name = "chris-driscol-api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
async-graphql = "7.0.7"
async-graphql-axum = "7.0.7"
async-graphql-relay = "0.4.6"
axum = "0.7.5"
tokio = { version = "1.40.0", features = ["full"] }
